# Copyright (c) 2026 Falcon. Personal fork of Brave.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

brave_browser_falcon_shields_sources = [
  "//brave/browser/falcon/shields/adblock_seed.cc",
  "//brave/browser/falcon/shields/adblock_seed.h",
]

brave_browser_falcon_shields_deps = [
  "//brave/components/brave_shields/content/browser",
  "//brave/components/brave_shields/core/browser",
  "//chrome/common",
  "//components/prefs",
  "//net",
  "//services/network/public/cpp",
  "//url",
]
