# Copyright (c) 2026 Falcon. Personal fork of Brave.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

brave_browser_falcon_download_sources = [
  "//brave/browser/falcon/download/aria2_service.cc",
  "//brave/browser/falcon/download/aria2_service.h",
  "//brave/browser/falcon/download/clipboard_monitor.cc",
  "//brave/browser/falcon/download/clipboard_monitor.h",
  "//brave/browser/falcon/download/download_categories.cc",
  "//brave/browser/falcon/download/download_categories.h",
  "//brave/browser/falcon/download/download_history.cc",
  "//brave/browser/falcon/download/download_history.h",
  "//brave/browser/falcon/download/download_interceptor.cc",
  "//brave/browser/falcon/download/download_interceptor.h",
  "//brave/browser/falcon/download/download_notifier.cc",
  "//brave/browser/falcon/download/download_notifier.h",
  "//brave/browser/falcon/download/download_scheduler.cc",
  "//brave/browser/falcon/download/download_scheduler.h",
  "//brave/browser/falcon/download/download_security.cc",
  "//brave/browser/falcon/download/download_security.h",
  "//brave/browser/falcon/download/download_tracker.cc",
  "//brave/browser/falcon/download/download_tracker.h",
  "//brave/browser/falcon/download/pref_names.cc",
  "//brave/browser/falcon/download/pref_names.h",
]

brave_browser_falcon_download_deps = [
  "//base",
  "//brave/components/constants",
  "//chrome/common",
  "//components/pref_registry",
  "//components/prefs",
  "//components/services/quarantine",
  "//crypto",
  "//content/public/browser",
  "//net",
  "//services/network/public/cpp",
  "//services/network/public/mojom",
  "//ui/base",
  "//ui/base/clipboard",
  "//ui/base/data_transfer_policy",
  "//ui/message_center/public/cpp",
  "//url",
]
